name: Update my readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  update-badges:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
